[package]
name = "merge_peaks"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bed-utils = "0.9.5"
genome = "0.3.0"
clap = { version = "4.5.18", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
flate2 = "1.0"
